name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  builds:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@V6

    - name: Set up JDK 21
      uses: actions/setup-java@V5
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Grant execute permission
      run: chmod +X ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
